name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Step
        run: dotnet build

      - name: Install packages
        working-directory: ./DotnetTemplate.Web
        run: npm install

      - name: Run
        working-directory: ./DotnetTemplate.Web
        run: npm run build

      - name: Run Test
        run: dotnet test

      - name: Typescript Test
        working-directory: ./DotnetTemplate.Web/Scripts/spec
        run: npm t

      - name: Run linting
        working-directory: ./DotnetTemplate.Web
        run: npm run lint

      - name: Webhook
        uses: magdemajt/trigger-webhook@v1
        with:
          url: '${{ secrets.WEBHOOK_URL }}'
          json: '{"text": "CI Job finished"}'
          headers: '{"Content-Type": "application/json"}'