name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Step
        run: dotnet build

      - name: Install packages
        working-directory: ./DotnetTemplate.Web
        run: npm install

      - name: Run
        working-directory: ./DotnetTemplate.Web
        run: npm run build