name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Me"